"""
literature_registry.py
----------------------
Machine-readable primary-source registry (physiology-evidence-2026-08).
"""

from __future__ import annotations

from typing import Any

from .config import LITERATURE_REGISTRY_VERSION

REFERENCES: dict[str, dict[str, Any]] = {
    "hillenbrand_1994_cpp_breathiness": {
        "title": "Acoustic Correlates of Breathy Vocal Quality",
        "authors": "Hillenbrand, Cleveland, Erickson",
        "year": 1994,
        "doi": "10.1044/jshr.3704.769",
        "pmid": None,
        "journal": "J Speech Lang Hear Res",
        "population": "healthy adults (elicited breathy/normal)",
        "task": "sustained vowels",
        "measurement": "periodicity / CPP-related cepstral prominence, H1 amplitude, spectral tilt",
        "supports": "cepstral/periodicity measures correlate with perceived breathiness; not geometric glottal closure",
        "limitations": "elicited breathiness; speech vowels; not singing skill cutoffs",
        "claim_supported": "CONDITIONAL",
    },
    "hillenbrand_1996_cpp_dysphonic": {
        "title": "Acoustic Correlates of Breathy Vocal Quality: Dysphonic Voices and Continuous Speech",
        "authors": "Hillenbrand, Houde",
        "year": 1996,
        "doi": "10.1044/jshr.3902.311",
        "population": "dysphonic + nonpathological",
        "task": "sustained vowel + connected speech",
        "measurement": "periodicity / first harmonic / spectral tilt",
        "supports": "periodicity predicts breathiness in clinical speech samples",
        "limitations": "dysphonia domain ≠ healthy singing coaching thresholds",
        "claim_supported": "CONDITIONAL",
    },
    "heman_ackah_2002_cpp_dysphonia": {
        "title": "The relationship between cepstral peak prominence and selected parameters of dysphonia",
        "authors": "Heman-Ackah, Michael, Goding",
        "year": 2002,
        "doi": "10.1016/s0892-1997(02)00067-x",
        "pmid": "12008652",
        "population": "pathological (RLN paralysis pre/post)",
        "task": "speech",
        "measurement": "CPPS vs perturbation/NHR",
        "supports": "CPPS correlates with dysphonia/breathiness ratings better than some perturbation metrics",
        "limitations": "clinical population; not individual anatomy; not singing norms",
        "claim_supported": "CONDITIONAL",
    },
    "saldias_2022_cpps_singing": {
        "title": "CPPS and Voice-Source Parameters: Objective Analysis of the Singing Voice",
        "authors": "Saldías et al.",
        "year": 2022,
        "doi": "10.1016/j.jvoice.2021.12.010",
        "population": "synthesized singing tones",
        "task": "singing-like scales",
        "measurement": "CPPS vs fo, vibrato, source tilt",
        "supports": "CPPS strongly confounded by fo and source-spectrum tilt in singing-like signals",
        "limitations": "in silico; warns against naive pre/post without fo control",
        "claim_supported": "SUPPORTED_FOR_CONFOUND_WARNING",
    },
    "brockmann_bauser_2021_cpp_intensity_f0": {
        "title": "Effects of Vocal Intensity and Fundamental Frequency on Cepstral Peak Prominence",
        "authors": "Brockmann-Bauser et al.",
        "year": 2021,
        "doi": "10.1016/j.jvoice.2019.11.015",
        "population": "voice disorders + healthy controls",
        "task": "speech/voice tasks",
        "measurement": "CPP vs intensity and fo",
        "supports": "CPP confounded by SPL and fo",
        "limitations": "not a glottal contact meter",
        "claim_supported": "SUPPORTED_FOR_CONFOUND_WARNING",
    },
    "boersma_1993_hnr": {
        "title": "Accurate short-term analysis of the fundamental frequency and the harmonics-to-noise ratio of a sampled sound",
        "authors": "Boersma",
        "year": 1993,
        "doi": None,
        "url": "https://www.fon.hum.uva.nl/paul/papers/Proceedings_1993.pdf",
        "population": "method paper / synthetic",
        "task": "algorithm definition",
        "measurement": "window-corrected autocorrelation HNR (Praat foundation)",
        "supports": "defines Praat-grade AC HNR method (window AC division, lag interpolation)",
        "limitations": "VAgent simplified AC HNR is NOT identical to Praat",
        "claim_supported": "SUPPORTED_FOR_DEFINITION",
    },
    "hanson_1997_h1h2": {
        "title": "Glottal characteristics of female speakers: Acoustic correlates (H1-H2 correction lineage)",
        "authors": "Hanson",
        "year": 1997,
        "doi": "10.1121/1.417906",
        "population": "female speakers",
        "task": "speech vowels",
        "measurement": "formant-corrected harmonic amplitudes",
        "supports": "raw H1-H2 confounded by F1; correction needed for source interpretation",
        "limitations": "speech; group tendencies",
        "claim_supported": "SUPPORTED",
    },
    "iseli_2004_h1h2_correction": {
        "title": "An improved correction formula for the estimation of harmonic magnitudes",
        "authors": "Iseli, Alwan",
        "year": 2004,
        "doi": "10.1121/1.4784741",
        "population": "synthetic vowels",
        "task": "method",
        "measurement": "H1*-H2* correction across vowels",
        "supports": "uncorrected H1-H2 is vowel-dependent; corrected version used as OQ proxy",
        "limitations": "proxy for OQ, not fold imaging",
        "claim_supported": "SUPPORTED",
    },
    "kreiman_2008_oq_h1h2": {
        "title": "The relationship between open quotient and H1*-H2*",
        "authors": "Kreiman, Iseli, Neubauer, Shue, Gerratt, Alwan",
        "year": 2008,
        "doi": "10.1121/1.4782813",
        "population": "speakers with high-speed video",
        "task": "vowel /i/, quality + fo variation",
        "measurement": "OQ vs H1*-H2*",
        "supports": "OQ↔H1*-H2* relationship weaker and speaker-dependent than often assumed",
        "limitations": "undermines strong individual OQ claims from H1*-H2*",
        "claim_supported": "CONTRADICTS_STRONG_MAPPING",
    },
    "kuang_2022_h1h2_linguistic": {
        "title": "On H1–H2 as an acoustic measure of linguistic phonation type",
        "authors": "Kuang / related JASA work",
        "year": 2022,
        "doi": "10.1121/10.0014175",
        "population": "linguistic phonation",
        "task": "speech",
        "measurement": "H1-H2 / H1*-H2*",
        "supports": "uncorrected H1-H2 misleading across vowels due to filter",
        "limitations": "linguistic not singing pedagogy",
        "claim_supported": "SUPPORTED",
    },
    "butte_2012_perturbation_singing": {
        "title": "Perturbation and Nonlinear Dynamic Analysis of Different Singing Styles",
        "authors": "Butte et al.",
        "year": 2009,
        "doi": "10.1016/j.jvoice.2007.10.009",
        "pmid": None,
        "population": "commercial singing styles",
        "task": "singing excerpts",
        "measurement": "jitter/shimmer",
        "supports": "vibrato confounds perturbation; opera high shimmer from vibrato/irregularity",
        "limitations": "not clinical cycle-exact jitter on standardized vowel",
        "claim_supported": "SUPPORTED_FOR_CONFOUND_WARNING",
    },
    "saldias_2024_perturbation_fo_vibrato": {
        "title": "High and Wide: Frequency, Intensity, and Vibrato Effects on Perturbation and Noise Measures",
        "authors": "Saldías et al.",
        "year": 2024,
        "doi": "10.1016/j.jvoice.2023.10.007",
        "population": "synthesized tones",
        "task": "in silico",
        "measurement": "jitter/shimmer/HNR vs fo, tilt, vibrato",
        "supports": "perturbation/HNR confounded by fo, intensity/tilt, vibrato extent",
        "limitations": "synthetic",
        "claim_supported": "SUPPORTED_FOR_CONFOUND_WARNING",
    },
    "titze_2006_sovt": {
        "title": "Voice training and therapy with a semi-occluded vocal tract: Rationale and scientific underpinnings",
        "authors": "Titze",
        "year": 2006,
        "doi": "10.1044/1092-4388(2006/035)",
        "population": "simulation",
        "task": "SOVT modeling",
        "measurement": "source-tract interaction / impedance matching",
        "supports": "SOVT/lip occlusion can improve phonatory economy via impedance matching",
        "limitations": "not disease treatment claim; coaching rationale only",
        "claim_supported": "CONDITIONAL",
    },
    "holmborg_1995_aerodynamic_egg": {
        "title": "Comparisons among aerodynamic, electroglottographic, and acoustic spectral measures of female voice",
        "authors": "Holmberg et al.",
        "year": 1995,
        "doi": "10.1044/jshr.3806.1212",
        "population": "female speakers",
        "task": "speech",
        "measurement": "aerodynamic / EGG / H1-H2",
        "supports": "spectral H1-H2 relates to open quotient / adduction tendencies with other measures",
        "limitations": "group-level; not audio-only individual anatomy",
        "claim_supported": "CONDITIONAL",
    },
}


METRIC_AUDIT: dict[str, dict[str, Any]] = {
    "cepstral_prominence_proxy_db": {
        "verdict": "RENAME",  # was cpp_db
        "literature_strength": "CONDITIONAL",
        "directly_measures": "simplified cepstral peak prominence vs trend (not CPPS/Praat-identical)",
        "correlates_with": "perceived breathiness / harmonic organization (group studies)",
        "does_not_measure": "glottal gap geometry, contact quotient, muscle activity",
        "evidence_family": "periodicity",
    },
    "hnr_ac_proxy_db": {
        "verdict": "RENAME",
        "literature_strength": "CONDITIONAL",
        "directly_measures": "simplified autocorrelation peak harmonicity proxy",
        "correlates_with": "periodicity / noise; related to voice quality dimensions",
        "does_not_measure": "true glottal efficiency, airflow, tissue collision",
        "evidence_family": "periodicity",  # SAME family as cepstral
    },
    "raw_h1_h2_proxy_db": {
        "verdict": "RENAME",
        "literature_strength": "WEAK",
        "directly_measures": "raw output-spectrum H1−H2 (no formant correction)",
        "correlates_with": "open-quotient / phonation-type tendencies ONLY after correction (H1*-H2*)",
        "does_not_measure": "actual open quotient without correction; fold contact",
        "evidence_family": "spectral_source",
    },
    "spectral_tilt_db_per_oct": {
        "verdict": "RESTRICT",
        "literature_strength": "WEAK",
        "directly_measures": "broadband spectral slope estimate",
        "correlates_with": "source tilt + tract + singer's formant confounds",
        "does_not_measure": "tract posture anatomy",
        "evidence_family": "spectral_source",
    },
    "f0_frame_period_perturbation_proxy_percent": {
        "verdict": "RENAME",
        "literature_strength": "WEAK",
        "directly_measures": "frame-F0-derived period-to-period proxy (NOT clinical cycle jitter)",
        "correlates_with": "local F0 irregularity under strict validity",
        "does_not_measure": "true cycle jitter; invalid under vibrato",
        "evidence_family": "temporal_stability",
    },
    "amplitude_window_shimmer_proxy_percent": {
        "verdict": "RENAME",
        "literature_strength": "WEAK",
        "directly_measures": "fixed-window peak amplitude variation proxy",
        "correlates_with": "amplitude irregularity under validity",
        "does_not_measure": "true cycle shimmer",
        "evidence_family": "temporal_stability",
    },
    "onset_slope_db_per_sec": {
        "verdict": "RESTRICT",
        "literature_strength": "CONDITIONAL",
        "directly_measures": "RMS envelope rise rate",
        "correlates_with": "hard/soft attack tendencies (weakly)",
        "does_not_measure": "glottal attack or EGG contact onset",
        "evidence_family": "onset",
    },
    "release_drop_db": {
        "verdict": "RESTRICT",
        "literature_strength": "WEAK",
        "directly_measures": "tail energy drop vs peak",
        "correlates_with": "offset abruptness (weak)",
        "does_not_measure": "abductory muscle state",
        "evidence_family": "release",
    },
    "envelope_smoothness_index": {
        "verdict": "RESTRICT",
        "literature_strength": "CONDITIONAL",
        "directly_measures": "custom log-RMS smoothness heuristic",
        "correlates_with": "intensity coordination smoothness",
        "does_not_measure": "abdominal pressure, lung volume, subglottal pressure",
        "evidence_family": "intensity_coordination",
    },
    "f0_continuity_ratio": {
        "verdict": "KEEP",
        "literature_strength": "CONDITIONAL",
        "directly_measures": "voiced F0 frame-to-frame continuity on siren",
        "correlates_with": "transition continuity / dropout",
        "does_not_measure": "TA/CT coordination",
        "evidence_family": "register_continuity",
    },
    "sustained_residual_f0_cents": {
        "verdict": "KEEP",
        "literature_strength": "CONDITIONAL",
        "directly_measures": "local trend-residual F0 variability on sustained regions",
        "correlates_with": "local pitch micro-instability (not global melody)",
        "does_not_measure": "pathology; distinct from intentional vibrato when flagged",
        "evidence_family": "temporal_stability",
    },
}


def registry_meta() -> dict[str, Any]:
    return {
        "literature_registry_version": LITERATURE_REGISTRY_VERSION,
        "reference_count": len(REFERENCES),
        "metric_audit_count": len(METRIC_AUDIT),
    }
